name: Node.js Package

on:
  push:
    branches:
      - master

jobs:
  build-and-publish:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Bump version and push tag
        id: tag_version
        uses: mathieudutour/github-tag-action@v5.5
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
      - name: Create a Github release
        uses: actions/create-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          tag_name: ${{ steps.tag_version.outputs.new_tag }}
          release_name: Release ${{ steps.tag_version.outputs.new_tag }}
          body: ${{ steps.tag_version.outputs.changelog }}
      - uses: actions/setup-node@v1
        with:
          always-auth: true
          registry-url: 'https://npm.pkg.github.com'
          node-version: 12
      - run: yarn
      - run: yarn build
      - uses: actions/upload-artifact@v2
        with:
          name: jdev-ui
          path: dist/

      - name: Set version
        run: yarn version --new-version ${{ steps.tag_version.outputs.new_tag }} --no-git-tag-version
      - name: Publish package
        run: yarn publish
        env:
          NODE_AUTH_TOKEN: ${{secrets.GITHUB_TOKEN}}
          GITHUB_TOKEN: ${{secrets.GITHUB_TOKEN}}
